// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: proto/data.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PrediccionClient is the client API for Prediccion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrediccionClient interface {
	// Sends a greeting
	AddPrediccion(ctx context.Context, in *PrediccionRequest, opts ...grpc.CallOption) (*PrediccionReply, error)
}

type prediccionClient struct {
	cc grpc.ClientConnInterface
}

func NewPrediccionClient(cc grpc.ClientConnInterface) PrediccionClient {
	return &prediccionClient{cc}
}

func (c *prediccionClient) AddPrediccion(ctx context.Context, in *PrediccionRequest, opts ...grpc.CallOption) (*PrediccionReply, error) {
	out := new(PrediccionReply)
	err := c.cc.Invoke(ctx, "/dataproto.Prediccion/addPrediccion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrediccionServer is the server API for Prediccion service.
// All implementations must embed UnimplementedPrediccionServer
// for forward compatibility
type PrediccionServer interface {
	// Sends a greeting
	AddPrediccion(context.Context, *PrediccionRequest) (*PrediccionReply, error)
	mustEmbedUnimplementedPrediccionServer()
}

// UnimplementedPrediccionServer must be embedded to have forward compatible implementations.
type UnimplementedPrediccionServer struct {
}

func (UnimplementedPrediccionServer) AddPrediccion(context.Context, *PrediccionRequest) (*PrediccionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPrediccion not implemented")
}
func (UnimplementedPrediccionServer) mustEmbedUnimplementedPrediccionServer() {}

// UnsafePrediccionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrediccionServer will
// result in compilation errors.
type UnsafePrediccionServer interface {
	mustEmbedUnimplementedPrediccionServer()
}

func RegisterPrediccionServer(s grpc.ServiceRegistrar, srv PrediccionServer) {
	s.RegisterService(&Prediccion_ServiceDesc, srv)
}

func _Prediccion_AddPrediccion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrediccionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrediccionServer).AddPrediccion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dataproto.Prediccion/addPrediccion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrediccionServer).AddPrediccion(ctx, req.(*PrediccionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Prediccion_ServiceDesc is the grpc.ServiceDesc for Prediccion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Prediccion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dataproto.Prediccion",
	HandlerType: (*PrediccionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addPrediccion",
			Handler:    _Prediccion_AddPrediccion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/data.proto",
}
