// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/data.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type PrediccionRequest struct {
	Team1                string   `protobuf:"bytes,1,opt,name=team1,proto3" json:"team1,omitempty"`
	Team2                string   `protobuf:"bytes,2,opt,name=team2,proto3" json:"team2,omitempty"`
	Score                string   `protobuf:"bytes,3,opt,name=score,proto3" json:"score,omitempty"`
	Phase                string   `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrediccionRequest) Reset()         { *m = PrediccionRequest{} }
func (m *PrediccionRequest) String() string { return proto.CompactTextString(m) }
func (*PrediccionRequest) ProtoMessage()    {}
func (*PrediccionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac8e6d38f431921d, []int{0}
}

func (m *PrediccionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrediccionRequest.Unmarshal(m, b)
}
func (m *PrediccionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrediccionRequest.Marshal(b, m, deterministic)
}
func (m *PrediccionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrediccionRequest.Merge(m, src)
}
func (m *PrediccionRequest) XXX_Size() int {
	return xxx_messageInfo_PrediccionRequest.Size(m)
}
func (m *PrediccionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrediccionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrediccionRequest proto.InternalMessageInfo

func (m *PrediccionRequest) GetTeam1() string {
	if m != nil {
		return m.Team1
	}
	return ""
}

func (m *PrediccionRequest) GetTeam2() string {
	if m != nil {
		return m.Team2
	}
	return ""
}

func (m *PrediccionRequest) GetScore() string {
	if m != nil {
		return m.Score
	}
	return ""
}

func (m *PrediccionRequest) GetPhase() string {
	if m != nil {
		return m.Phase
	}
	return ""
}

// The response message containing the greetings
type PrediccionReply struct {
	Team1                string   `protobuf:"bytes,1,opt,name=team1,proto3" json:"team1,omitempty"`
	Team2                string   `protobuf:"bytes,2,opt,name=team2,proto3" json:"team2,omitempty"`
	Score                string   `protobuf:"bytes,3,opt,name=score,proto3" json:"score,omitempty"`
	Phase                string   `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrediccionReply) Reset()         { *m = PrediccionReply{} }
func (m *PrediccionReply) String() string { return proto.CompactTextString(m) }
func (*PrediccionReply) ProtoMessage()    {}
func (*PrediccionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac8e6d38f431921d, []int{1}
}

func (m *PrediccionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrediccionReply.Unmarshal(m, b)
}
func (m *PrediccionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrediccionReply.Marshal(b, m, deterministic)
}
func (m *PrediccionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrediccionReply.Merge(m, src)
}
func (m *PrediccionReply) XXX_Size() int {
	return xxx_messageInfo_PrediccionReply.Size(m)
}
func (m *PrediccionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PrediccionReply.DiscardUnknown(m)
}

var xxx_messageInfo_PrediccionReply proto.InternalMessageInfo

func (m *PrediccionReply) GetTeam1() string {
	if m != nil {
		return m.Team1
	}
	return ""
}

func (m *PrediccionReply) GetTeam2() string {
	if m != nil {
		return m.Team2
	}
	return ""
}

func (m *PrediccionReply) GetScore() string {
	if m != nil {
		return m.Score
	}
	return ""
}

func (m *PrediccionReply) GetPhase() string {
	if m != nil {
		return m.Phase
	}
	return ""
}

func init() {
	proto.RegisterType((*PrediccionRequest)(nil), "dataproto.PrediccionRequest")
	proto.RegisterType((*PrediccionReply)(nil), "dataproto.PrediccionReply")
}

func init() { proto.RegisterFile("proto/data.proto", fileDescriptor_ac8e6d38f431921d) }

var fileDescriptor_ac8e6d38f431921d = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x49, 0x2c, 0x49, 0xd4, 0x03, 0x33, 0x85, 0x38, 0x41, 0x6c, 0x30, 0x53, 0x29,
	0x9b, 0x4b, 0x30, 0xa0, 0x28, 0x35, 0x25, 0x33, 0x39, 0x39, 0x33, 0x3f, 0x2f, 0x28, 0xb5, 0xb0,
	0x34, 0xb5, 0xb8, 0x44, 0x48, 0x84, 0x8b, 0xb5, 0x24, 0x35, 0x31, 0xd7, 0x50, 0x82, 0x51, 0x81,
	0x51, 0x83, 0x33, 0x08, 0xc2, 0x81, 0x89, 0x1a, 0x49, 0x30, 0x21, 0x44, 0x8d, 0x40, 0xa2, 0xc5,
	0xc9, 0xf9, 0x45, 0xa9, 0x12, 0xcc, 0x10, 0x51, 0x30, 0x07, 0x24, 0x5a, 0x90, 0x91, 0x58, 0x9c,
	0x2a, 0xc1, 0x02, 0x11, 0x05, 0x73, 0x94, 0x32, 0xb9, 0xf8, 0x91, 0x2d, 0x2b, 0xc8, 0xa9, 0xa4,
	0x95, 0x55, 0x46, 0x91, 0x5c, 0x5c, 0x08, 0xab, 0x84, 0xbc, 0xb9, 0x78, 0x13, 0x53, 0x52, 0x90,
	0x04, 0x64, 0xf4, 0xe0, 0x41, 0xa0, 0x87, 0xe1, 0x7f, 0x29, 0x29, 0x1c, 0xb2, 0x05, 0x39, 0x95,
	0x4a, 0x0c, 0x4e, 0x4a, 0x51, 0x0a, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9,
	0xfa, 0xd9, 0x89, 0x25, 0xa9, 0x45, 0x99, 0x79, 0xe5, 0xfa, 0x01, 0x20, 0xe5, 0xc5, 0xfa, 0x60,
	0x5d, 0x49, 0x6c, 0x60, 0xca, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x77, 0x9c, 0xcf, 0x33, 0x7c,
	0x01, 0x00, 0x00,
}
